import os

# VARIABLES

MODEL_TARGET = os.environ.get("MODEL_TARGET")
MLFLOW_TRACKING_URI = os.environ.get("MLFLOW_TRACKING_URI")
MLFLOW_MODEL_NAME = os.environ.get("MLFLOW_MODEL_NAME")
MLFLOW_EXPERIMENT = os.environ.get("MLFLOW_EXPERIMENT")
